codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        branches:
          - master
          - dev
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  # Django 相关
  - "*/migrations/*"
  - "manage.py"
  - "*/settings.py"
  - "*/wsgi.py"
  - "*/asgi.py"
  
  # 测试相关
  - "*/tests/*"
  - "*/test_*.py"
  - "*/*test*.py"
  
  # 静态文件和模板
  - "*/static/*"
  - "*/templates/*"
  - "*/collectedstatic/*"
  
  # 国际化文件
  - "*/locale/*"
  - "**/*.po"
  - "**/*.mo"
  
  # 文档和部署
  - "*/docs/*"
  - "*/deploy/*"
  - "README*.md"
  - "LICENSE"
  - "Dockerfile"
  - "docker-compose*.yml"
  - "*.yaml"
  - "*.yml"
  
  # 开发环境
  - "*/venv/*"
  - "*/__pycache__/*"
  - "*.pyc"
  - ".coverage"
  - "coverage.xml"
  
  # 日志文件
  - "*/logs/*"
  - "*.log"
  
  # 特定文件
  - "*/whoosh_cn_backend.py"  # 搜索后端
  - "*/elasticsearch_backend.py"  # 搜索后端
  - "*/MemcacheStorage.py"  # 缓存存储
  - "*/robot.py"  # 机器人相关
  
  # 配置文件
  - "codecov.yml"
  - ".coveragerc"
  - "requirements*.txt"
