# Generated by Django 5.2.9 on 2025-12-25 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_idx_type_status_pub_article_idx_status_views_and_more'),
        ('comments', '0003_alter_comment_options_remove_comment_created_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'parent_comment', 'is_enable'], name='idx_art_parent_enable'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_enable', '-id'], name='idx_enable_id'),
        ),
    ]
