# Generated by Django 5.2.9 on 2026-01-22 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_idx_art_parent_enable_comment_idx_enable_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('👍', 'thumbs_up'), ('👎', 'thumbs_down'), ('❤️', 'heart'), ('😄', 'laugh'), ('🎉', 'hooray'), ('😕', 'confused'), ('🚀', 'rocket'), ('👀', 'eyes')], max_length=10, verbose_name='reaction type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comments.comment', verbose_name='comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'comment reaction',
                'verbose_name_plural': 'comment reactions',
                'indexes': [models.Index(fields=['comment', 'reaction_type'], name='idx_comment_reaction')],
                'unique_together': {('comment', 'user', 'reaction_type')},
            },
        ),
    ]
