# Generated by Django 5.2.11 on 2026-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bloguser_options_remove_bloguser_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='bio'),
        ),
    ]
