# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, to='comments.Comment', verbose_name='评论集合'),
        ),
    ]
