# Generated by Django 4.2.1 on 2023-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_blogsettings_global_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='comment_need_review',
            field=models.BooleanField(default=False, verbose_name='评论是否需要审核'),
        ),
    ]
