# Generated by Django 4.2.1 on 2023-05-09 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_blogsettings_comment_need_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsettings',
            old_name='analyticscode',
            new_name='analytics_code',
        ),
        migrations.RenameField(
            model_name='blogsettings',
            old_name='beiancode',
            new_name='beian_code',
        ),
        migrations.RenameField(
            model_name='blogsettings',
            old_name='sitename',
            new_name='site_name',
        ),
    ]
