# Generated by Django 5.2.9 on 2025-12-25 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['type', 'status', '-pub_time'], name='idx_type_status_pub'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-views'], name='idx_status_views'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status', 'type'], name='idx_author_status_type'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='idx_category_status'),
        ),
    ]
