# Generated by Django 5.2.8 on 2025-12-10 12:08

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('last_modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modify time')),
                ('version_number', models.PositiveIntegerField(verbose_name='version number')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', mdeditor.fields.MDTextField(verbose_name='body')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='version comment')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blog.article', verbose_name='article')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='editor')),
            ],
            options={
                'verbose_name': 'article version',
                'verbose_name_plural': 'article versions',
                'ordering': ['-version_number'],
                'unique_together': {('article', 'version_number')},
            },
        ),
    ]
