# Generated by Django 5.2.1 on 2025-05-17 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_blogsettings_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation time"
                    ),
                ),
                (
                    "last_modify_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="modify time"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "favorite",
                "verbose_name_plural": "favorite",
                "unique_together": {("user", "article")},
            },
        ),
    ]
