# Generated by Django 5.2.9 on 2025-12-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_idx_type_status_pub_article_idx_status_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='color_scheme',
            field=models.CharField(choices=[('purple', '紫色主题 - Purple Dream'), ('blue', '蓝色主题 - Ocean Blue'), ('green', '绿色主题 - Forest Green'), ('orange', '橙色主题 - Sunset Orange'), ('pink', '粉色主题 - Cherry Blossom'), ('red', '红色主题 - Ruby Red'), ('indigo', '靛蓝主题 - Midnight Indigo'), ('teal', '青色主题 - Teal Wave')], default='purple', help_text='选择网站的主题配色方案', max_length=20, verbose_name='配色方案'),
        ),
    ]
