# Generated by Django 4.2.5 on 2023-09-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owntracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owntracklog',
            options={'get_latest_by': 'creation_time', 'ordering': ['creation_time'], 'verbose_name': 'OwnTrackLogs', 'verbose_name_plural': 'OwnTrackLogs'},
        ),
        migrations.RenameField(
            model_name='owntracklog',
            old_name='created_time',
            new_name='creation_time',
        ),
    ]
